### ISSUE TITLE
Validate polyfit emulator

### ISSUE THREAD

**Issue by Chris-Pedersen** [Chris-Pedersen/LaCE_manager#41]
The strong noise spikes in the emulated P1D mean we are artificially sensitive to the H(z) used in reconstruction. It's worth taking a quick look again at the polyfit emulator as this would smooth out some of these features. We start with testing the emulator predictions on the nu and h sims (fig 5 of https://arxiv.org/pdf/2011.15127.pdf), using a 4th degree polynomial.

![poly_nu_h](https://user-images.githubusercontent.com/16047009/140567951-3f3c47f6-f350-431a-96f2-c97b9b4d1993.png)

It's hard to judge the performance here as we mostly see the noise spikes. So next we fit the "true" data also to a 4th degree polynomial, and plot the error again

![poly_nu_h_fit](https://user-images.githubusercontent.com/16047009/140567960-bcc0f916-101e-4b0c-ad01-f173bc04c303.png)

We see a bit of a spike at low k, to 2.5% but overall the error is pretty good. I'll try some higher order polynomials next.

**Comment by andreufont** [comment]
These spikes are ok, there is cosmic variance in the box. Maybe its time to quantify it with the different seed sims

**Comment by Chris-Pedersen** [comment]
The cosmic variance should be the same in the training and test sims though so not sure it's just this.

>Maybe its time to quantify it with the different seed sims

I think so. We could compare how well the polyfit and GP emulator recover parameters from the sims with different numerical seeds.

**Comment by andreufont** [comment]
I meant the spikes when testing the emulator versus the raw power, not versus the smoothed power.

**Comment by andreufont** [comment]
Sorry, I accidentally closed the issue, I just wanted to add a comment...

**Comment by Chris-Pedersen** [comment]
Ahh I see, I was referring to the ~2.5% error at low k and z=2.0

**Comment by Chris-Pedersen** [comment]
Hmm possibly, I never quite went as far with this as I wanted to, i.e. the full leave-one-out validation test.

**Comment by andreufont** [comment]
We have been using successfully the polyfit emulator, so let's close the issue as it is clear we are not going to do more testing on this any time soon.
