### ISSUE TITLE
Change LYA_EMU_REPO to LACE_REPO

### ISSUE THREAD

**Issue by andreufont** [Chris-Pedersen/LaCE_manager#50]
We use this environmental variable in the code, probably better to rename it to LACE_REPO? 

I guess we can wait until we decide on the submodule naming.

**Comment by Chris-Pedersen** [comment]
Yes good point! Once we settle on a new name we should update this

**Comment by andreufont** [comment]
The new `lace` repo in igmhub uses LACE_REPO to find the simulated p1d and setup the emulator. 

In this sense, it might be ok to use this other name LYA_EMU_REPO in the `lace_manager` repo (this one).

**Comment by andreufont** [comment]
(although I guess it would be better to change to LACE_MANAGER_REPO)

**Comment by andreufont** [comment]
Fixed in #57
