### ISSUE TITLE
Consider removing pivot_scalar

### ISSUE THREAD

**Issue by andreufont** [Chris-Pedersen/LaCE_manager#53]
There are 40 lines that use pivot_scalar in the code, but I'm not sure why we need this. @Chris-Pedersen , where do you use it?

I noticed, for instance, that we had a bug in shift_primordial_pivot when using a different pivot_scalar for cosmologies with running. I added an assert to identify this problem, but I wonder whether we can get rid of this altogether.

**Comment by Chris-Pedersen** [comment]
Happy for this to go!

**Comment by andreufont** [comment]
Being addressed in #75
