### ISSUE TITLE
Avoid interpolation when making mocks from polyfit models

### ISSUE THREAD

**Issue by andreufont** [Chris-Pedersen/LaCE_manager#69]
Not urgent, but writing down in case we ever want to improve this.

When constructing a P1D_MPGADGET object with the polyfit option, we call get_polyfit_p1d_Mpc to get the polyfit evaluated at the simulation wavenumbers k_Mpc. A few lines below, we interpolate these (with scipy interp1d, cubic splines) to the wavenumbers of the data (k_kms). Since polyfit is a continuous function, there is no need to add this extra interpolation, we could just hold the polynomial function, and evaluate it at the required k_kms / convertion_factor. 

Not sure if this has anything to do with the small biases when using polyfit emulators, but worth trying at some point.

**Comment by Chris-Pedersen** [comment]
This is a great point, thanks for noticing this. In principle it'd be quick to test if the bias is a consequence of this, as the bias is present in the compressed chains which run fast. Will see if I have time to look at this next weel.

**Comment by andreufont** [comment]
To quantify this, I did the following (for the central sim):
 - generate a data_MPGadget mock with the polyfit option, that currently does the unnecessary interpolation
 - evaluate directly the polynomial in velocity units, and compute the ratio

![interpolated_poly_mock](https://user-images.githubusercontent.com/3873863/165970803-d3b86195-e64d-443d-9ce6-34ef7f15231f.png)

The agreement is basically perfect at high-k, but there are clear numerical artefacts at low-k that look similar to the disagreements I was seeing in the prediction.pdf files from the chains.

I'll dig a bit deeper.

**Comment by andreufont** [comment]
This is being addressed in #70 , about to be merged.
