### ISSUE TITLE
Debug sampler runs for diff_z simulation

### ISSUE THREAD

**Issue by andreufont** [Chris-Pedersen/LaCE_manager#71]
I'm finding some weird interpolation errors when running the sampler on the diff_z simulation.

This is the one that has the same z binning than Chabanier et al. (2019), so it should be better for forecasting (in the others we are dropping redshift bins).

Will dig deeper later in the week.

**Comment by Chris-Pedersen** [comment]
As in the code crashes, or results look weird? I tested recovering compressed parameters on the diff_z when I merged, but haven't tested it since we switched to the polyfit emulator.

**Comment by andreufont** [comment]
Nevermind, it was a red herring. The problem was that I have been using z_max=5 in the emulator / mock settings. While the standard sims have a maximum redshift of z=4.5 the diff_z sim has an output at z=4.6. This causes errors in mean_flux_model since the fiducial IGM history is only computed up to z=4.5, so it does not know how to extrapolate to z=4.6. 

In the short term, I can solve this by setting z_max=4.5 in the config file, so that that high-z point is not generated. 

In the long term, we could use the diff_z sim to set the fiducial history, although it does not have the z=2 output (not sure why, I guess because it wasn't measured in eBOSS). So let's probably leave it as is.
