### ISSUE TITLE
model_p3d_arinyo

### ISSUE THREAD

**Issue by jchavesmontero** [Chris-Pedersen/LaCE_manager#80]
I think that there is an inconsistency between Eq. 4.5 of Givans+2022 and line 

https://github.com/Chris-Pedersen/LaCE_manager/blob/5739e4681c4a4910a1270cb364067b45570cf187/lace_manager/p3d/model_p3d_arinyo.py#L126

d1_kvav should be elevated to d1_av

**Comment by andreufont** [comment]
Right, I remember now. We decided to sample `kvav = kv**av` instead of sampling `kv`, I don't remember why. We did add a comment somewhere about this (the units are Mpc^av), and the name of the parameter (`d1_kvav` instead of `d1_kv`) also hints at this. We could maybe add another comment.

**Comment by jchavesmontero** [comment]
Thanks!
